package com.guonl.dao;

import com.guonl.po.LogsSqlRecord;
import com.guonl.po.LogsSqlRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogsSqlRecordMapper {
    long countByExample(LogsSqlRecordExample example);

    int deleteByExample(LogsSqlRecordExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LogsSqlRecord record);

    int insertSelective(LogsSqlRecord record);

    List<LogsSqlRecord> selectByExample(LogsSqlRecordExample example);

    LogsSqlRecord selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") LogsSqlRecord record, @Param("example") LogsSqlRecordExample example);

    int updateByExample(@Param("record") LogsSqlRecord record, @Param("example") LogsSqlRecordExample example);

    int updateByPrimaryKeySelective(LogsSqlRecord record);

    int updateByPrimaryKey(LogsSqlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_sql_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LogsSqlRecord selectOneByExample(LogsSqlRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_sql_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<LogsSqlRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_sql_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<LogsSqlRecord> list, @Param("selective") LogsSqlRecord.Column ... selective);
}