package com.guonl.dao;

import com.guonl.po.SqlLogRecord;
import com.guonl.po.SqlLogRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqlLogRecordMapper {
    long countByExample(SqlLogRecordExample example);

    int deleteByExample(SqlLogRecordExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SqlLogRecord record);

    int insertSelective(SqlLogRecord record);

    List<SqlLogRecord> selectByExample(SqlLogRecordExample example);

    SqlLogRecord selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") SqlLogRecord record, @Param("example") SqlLogRecordExample example);

    int updateByExample(@Param("record") SqlLogRecord record, @Param("example") SqlLogRecordExample example);

    int updateByPrimaryKeySelective(SqlLogRecord record);

    int updateByPrimaryKey(SqlLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_log_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SqlLogRecord selectOneByExample(SqlLogRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_log_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SqlLogRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_log_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SqlLogRecord> list, @Param("selective") SqlLogRecord.Column ... selective);
}