package com.guonl.po;

import java.util.Date;

public class BlackTableRule {
    private Integer id;

    private Integer parentId;

    private String bTableName;

    private Integer isBlack;

    private String blackField;

    private Date createdAt;

    private Date updatedAt;

    private Boolean isDel;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getbTableName() {
        return bTableName;
    }

    public void setbTableName(String bTableName) {
        this.bTableName = bTableName == null ? null : bTableName.trim();
    }

    public Integer getIsBlack() {
        return isBlack;
    }

    public void setIsBlack(Integer isBlack) {
        this.isBlack = isBlack;
    }

    public String getBlackField() {
        return blackField;
    }

    public void setBlackField(String blackField) {
        this.blackField = blackField == null ? null : blackField.trim();
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_table_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static BlackTableRule.Builder builder() {
        return new BlackTableRule.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table black_table_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private BlackTableRule obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new BlackTableRule();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.id
         *
         * @param id the value for black_table_rule.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.parent_id
         *
         * @param parentId the value for black_table_rule.parent_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder parentId(Integer parentId) {
            obj.setParentId(parentId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.b_table_name
         *
         * @param bTableName the value for black_table_rule.b_table_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bTableName(String bTableName) {
            obj.setbTableName(bTableName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.is_black
         *
         * @param isBlack the value for black_table_rule.is_black
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isBlack(Integer isBlack) {
            obj.setIsBlack(isBlack);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.black_field
         *
         * @param blackField the value for black_table_rule.black_field
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder blackField(String blackField) {
            obj.setBlackField(blackField);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.created_at
         *
         * @param createdAt the value for black_table_rule.created_at
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createdAt(Date createdAt) {
            obj.setCreatedAt(createdAt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.updated_at
         *
         * @param updatedAt the value for black_table_rule.updated_at
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updatedAt(Date updatedAt) {
            obj.setUpdatedAt(updatedAt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column black_table_rule.is_del
         *
         * @param isDel the value for black_table_rule.is_del
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isDel(Boolean isDel) {
            obj.setIsDel(isDel);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public BlackTableRule build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table black_table_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        parentId("parent_id"),
        bTableName("b_table_name"),
        isBlack("is_black"),
        blackField("black_field"),
        createdAt("created_at"),
        updatedAt("updated_at"),
        isDel("is_del");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table black_table_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}