package com.guonl.po;

import java.util.Date;

public class LogsSqlRecord {
    private Integer id;

    private String tableName;

    private String executeSql;

    private String sqlType;

    private String wherePara;

    private String updatePara;

    private String operator;

    private Date createdAt;

    private Date updatedAt;

    private Boolean isDel;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    public String getExecuteSql() {
        return executeSql;
    }

    public void setExecuteSql(String executeSql) {
        this.executeSql = executeSql == null ? null : executeSql.trim();
    }

    public String getSqlType() {
        return sqlType;
    }

    public void setSqlType(String sqlType) {
        this.sqlType = sqlType == null ? null : sqlType.trim();
    }

    public String getWherePara() {
        return wherePara;
    }

    public void setWherePara(String wherePara) {
        this.wherePara = wherePara == null ? null : wherePara.trim();
    }

    public String getUpdatePara() {
        return updatePara;
    }

    public void setUpdatePara(String updatePara) {
        this.updatePara = updatePara == null ? null : updatePara.trim();
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_sql_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static LogsSqlRecord.Builder builder() {
        return new LogsSqlRecord.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logs_sql_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private LogsSqlRecord obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new LogsSqlRecord();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.id
         *
         * @param id the value for logs_sql_record.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.table_name
         *
         * @param tableName the value for logs_sql_record.table_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tableName(String tableName) {
            obj.setTableName(tableName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.execute_sql
         *
         * @param executeSql the value for logs_sql_record.execute_sql
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder executeSql(String executeSql) {
            obj.setExecuteSql(executeSql);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.sql_type
         *
         * @param sqlType the value for logs_sql_record.sql_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder sqlType(String sqlType) {
            obj.setSqlType(sqlType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.where_para
         *
         * @param wherePara the value for logs_sql_record.where_para
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder wherePara(String wherePara) {
            obj.setWherePara(wherePara);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.update_para
         *
         * @param updatePara the value for logs_sql_record.update_para
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updatePara(String updatePara) {
            obj.setUpdatePara(updatePara);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.operator
         *
         * @param operator the value for logs_sql_record.operator
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder operator(String operator) {
            obj.setOperator(operator);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.created_at
         *
         * @param createdAt the value for logs_sql_record.created_at
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createdAt(Date createdAt) {
            obj.setCreatedAt(createdAt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.updated_at
         *
         * @param updatedAt the value for logs_sql_record.updated_at
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updatedAt(Date updatedAt) {
            obj.setUpdatedAt(updatedAt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column logs_sql_record.is_del
         *
         * @param isDel the value for logs_sql_record.is_del
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isDel(Boolean isDel) {
            obj.setIsDel(isDel);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public LogsSqlRecord build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table logs_sql_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        tableName("table_name"),
        executeSql("execute_sql"),
        sqlType("sql_type"),
        wherePara("where_para"),
        updatePara("update_para"),
        operator("operator"),
        createdAt("created_at"),
        updatedAt("updated_at"),
        isDel("is_del");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table logs_sql_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}